name: sales_nsm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7  # Untuk mengambil foto & video dari galeri/kamera
  permission_handler: ^12.0.0  # Untuk mengelola izin akses kamera & galeri
  http: ^1.3.0
  shared_preferences: ^2.2.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  video_player: ^2.8.2
  flutter_riverpod: ^2.4.9
  badges: ^3.1.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/images/NSM.png"  # Pastikan gambar ini ada
  adaptive_icon_background: "#ffffff"  # Untuk Android adaptive icon
  adaptive_icon_foreground: "assets/images/NSM.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/nsm.png
    - assets/images/JENIS-JENIS-POMPA-BETON.jpg
    - assets/images/standart.png
    - assets/images/longboom.png
    - assets/images/super-longboom.png
    - assets/images/kodok.png
    - assets/images/logo-CV.png
    - assets/images/mini.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
