name: aplikasi_nota
description: "Aplikasi nota / invoice offline berbasis Flutter & SQLite"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ===============================
  # DATABASE (OFFLINE)
  # ===============================
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4

  # ===============================
  # STATE MANAGEMENT (RINGAN)
  # ===============================
  provider: ^6.1.2

  # ===============================
  # FORMAT TANGGAL & UANG
  # ===============================
  intl: ^0.19.0

  # ===============================
  # PDF INVOICE & PRINT
  # ===============================
  pdf: ^3.11.0
  printing: ^5.13.0

  # ===============================
  # ICON
  # ===============================
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
    - assets/images/wm.webp
