// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Gerl9sLtsiZVdGyIkg6HlztwuGWUMMw',
    appId: '1:267587029292:web:c1bcf2d2dabb2ab10a0489',
    messagingSenderId: '267587029292',
    projectId: 'niaga-solusi-mandiri-c1186',
    authDomain: 'niaga-solusi-mandiri-c1186.firebaseapp.com',
    storageBucket: 'niaga-solusi-mandiri-c1186.firebasestorage.app',
    measurementId: 'G-JJMR6JCJ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHhbL9NMZYxUfq2NTuljeqa_V2cgmYQo',
    appId: '1:267587029292:android:be9775e29f0cd9ba0a0489',
    messagingSenderId: '267587029292',
    projectId: 'niaga-solusi-mandiri-c1186',
    storageBucket: 'niaga-solusi-mandiri-c1186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjZ_1x0ztwZRxz4MO84qdMSdukwzrcfFo',
    appId: '1:267587029292:ios:870c61ce90fd469c0a0489',
    messagingSenderId: '267587029292',
    projectId: 'niaga-solusi-mandiri-c1186',
    storageBucket: 'niaga-solusi-mandiri-c1186.firebasestorage.app',
    iosBundleId: 'com.example.salesNsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjZ_1x0ztwZRxz4MO84qdMSdukwzrcfFo',
    appId: '1:267587029292:ios:870c61ce90fd469c0a0489',
    messagingSenderId: '267587029292',
    projectId: 'niaga-solusi-mandiri-c1186',
    storageBucket: 'niaga-solusi-mandiri-c1186.firebasestorage.app',
    iosBundleId: 'com.example.salesNsm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Gerl9sLtsiZVdGyIkg6HlztwuGWUMMw',
    appId: '1:267587029292:web:2996f59ca90fd7e20a0489',
    messagingSenderId: '267587029292',
    projectId: 'niaga-solusi-mandiri-c1186',
    authDomain: 'niaga-solusi-mandiri-c1186.firebaseapp.com',
    storageBucket: 'niaga-solusi-mandiri-c1186.firebasestorage.app',
    measurementId: 'G-3PEZ5Y1Y2T',
  );
}
